language:  generic

notifications:
  slack:
    rooms:
      - nozeio:LIFY1Jtkx0FRcLq3u1WliHRZ
      - zeeql:odi4PEJUdmDPkBfjhHIaSdrS
      - apacheexpress:9z2IfvxZfENp0TFmiYCgyUKz

matrix:
    include:
        - os:   osx
          osx_image: xcode8.3
        - os:   osx
          osx_image: xcode9 - fails decodable in testSchemaWithInlineArrayToMany
        - os:   osx
          osx_image: xcode9.2
        - os:   osx
          osx_image: xcode9.3beta

script:
    - make
